modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ProgrammerLP/create-more-seats/issues"
license = "AGPL-3"

[[mods]]
modId = "cms"
version = "${version}"
displayName = "Create More Seats"
authors = "Adeptstack - ProgrammerLP"
description = '''
Mod that adds 2 types of modern seats for trains or similiar.
'''
logoFile = "cms_logo.png"

[[dependencies.cms]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cms]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cms]]
modId="create"
mandatory=true
versionRange="[6.0.7,]"
ordering="NONE"
side="BOTH"
