modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ProgrammerLP/create-more-seats/issues"
license = "AGPL-3"

[[mods]]
modId = "cms"
version = "${version}"
displayName = "Create More Seats"
authors = "Adeptstack - ProgrammerLP"
description = '''
Mod that adds 2 types of modern seats for trains or similiar.
'''
logoFile = "cms_logo.png"

[[dependencies.cms]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cms]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cms]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cms]]
modId = "create"
type = "required"
versionRange = "[6.0.6,]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cms.mixins.json"
